apiVersion: v1
kind: Service
metadata:
  name: css-frontend
  labels:
    app: css-frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: css-frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80