apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
{{ include "css-backend.labels" . | indent 4 }}
data:
{{- range $k, $v := .Values.configMap.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
